### PR TITLE
eb conforming setup

### PR DESCRIPTION
**Pull request by cmeesters**
Hi,

I was trying to create an easyconfig file for distribution of your package within the HPC easybuild community and was unable to do so with the existing setup.py.

Hence, this PR contains my patch. Please have a look into this, whether you like it (whether it does do the job for you) or not.

Cheers
Christian

### CODE REVIEW

**Comment by PaulVanSchayck** [comment]
Hi Christian,

This PR looks fine. Out of interest, the main purpose of this code is to be run within an iRODS ruleset. Why would want to include this in a HPC environment?

**Comment by cmeesters** [comment]
Hoi Paul,

Indeed. The scenario is this: We provide iRODS binaries on our Cluster (on other sites on campus, too). My aim is to run automated workflows which (among other things) do archiving to our iRODS instance. This should have an option to also feed in metadata obtained from schema files. Hence, I have written a script which calls 'imeta add' for every avu-triplet in the respective dict.

Is this approach too un-orthodox?

Cheers
Christian

**Comment by PaulVanSchayck** [comment]
Hi Christian,

No, I guess not! A more classical iRODS setup would be to, instead of your script, have these functions run in policy rules on the iRODS server directly. I can't judge if that makes sense in your use case. 

In case you missed it, this code was written to be used from these ruleset functions:
https://github.com/MaastrichtUniversity/irods_avu_json-ruleset

The core.py contains the functions and the policies:
https://github.com/MaastrichtUniversity/irods_avu_json-ruleset/blob/master/rules/core.py

**Comment by joergsteinkamp** [comment]
Hi Paul,
I'm the admin of Christian's iRODS-Servers and I would prefer to have the avu_json stuff outside the server on client side. On the one side I do not have the python rule engine installed (and don't indent todo) and it'll be easier to integrate error checking in the metadata file on client side, than on server side since iRODS error messages are not really user-friendly. If it does not interfere the server side installation, I'd also be happy, if you could merge Christians changes.
Jörg

**Comment by PaulVanSchayck** [comment]
Sorry for the delay. There is no issue. I guess you would also like to have the pip packages rebuilt?

**Comment by cmeesters** [comment]
Thank you.

Well, you create a new release, if you think new functionality or fixes merit a new release. Meanwhile, I have my little patch for eb.

As for the script I mentioned: This is not of interest, I suppose? It builds upon the python code in this repo (and needs extension to cover more checks) and is intended to run on the client side, only. Hence, it is outside the original and intended realm of this repo.   I would be interested what you think about this idea, anyway.

Cheers,
Christian

**Comment by PaulVanSchayck** [comment]
I've released it as a new version, and build the new pip package. Thanks for the contribution.

I think think the idea you're describing is interesting. I would be happy to have a look at, if it's available in a public repo somewhere. I agree it's outside the scope of this repo.

**Comment by cmeesters** [comment]
Not in a repo yet and I am pretty busy. I was contemplating to put it in this repo. So either
- I put it in another PR when I find the time
- or send it to you by other means (I am unable to find an email address which is 100% associated with your name)
- or open a repo for this anyway.

Anything you prefer?

Cheers
Christian

**Pull request merged**
